// <auto-generated />
using System;
using Eventshuffle.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eventshuffle.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240824093852_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Eventshuffle.src.Eventshuffle.Domain.Entities.DateOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("People")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("DateOption");
                });

            modelBuilder.Entity("Eventshuffle.src.Eventshuffle.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("People")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Eventshuffle.src.Eventshuffle.Domain.Entities.DateOption", b =>
                {
                    b.HasOne("Eventshuffle.src.Eventshuffle.Domain.Entities.Event", null)
                        .WithMany("DateOptions")
                        .HasForeignKey("EventId");
                });

            modelBuilder.Entity("Eventshuffle.src.Eventshuffle.Domain.Entities.Event", b =>
                {
                    b.Navigation("DateOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
